### ISSUE TITLE
Mettre en place des redirections de l'ancien site vers le nouveau

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/accessibilite.numerique.gouv.fr#101]
Bonjour,

J'étais tranquillement en train de faire un audit et puis je navigue sur l'ancien site du RGAA et hop, une page 404. Pourriez-vous mettre en place des redirections vers le nouveau site s'il vous plaît ?

**Comment by okeul** [comment]
Exemple sur https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#contenu
<img width="818" alt="Capture d’écran 2022-11-16 à 16 05 18" src="https://user-images.githubusercontent.com/6248074/202216986-bbf00cba-f4b8-4ebb-990f-34bd40a63cfd.png">

**Comment by jonathanulco** [comment]
Des ressources complémentaires qui pourraient être utile 

https://www.nginx.com/blog/creating-nginx-rewrite-rules/

https://httpd.apache.org/docs/2.4/fr/mod/mod_rewrite.html

**Comment by ChristianVOLLE** [comment]
En allant à https://www.numerique.gouv.fr/publications/rgaa-accessibilite/, j'ai désormais "403 Forbidden"
