### ISSUE TITLE
Archives des versions précédentes 

### ISSUE THREAD

**Issue by armonyaltinier** [DISIC/accessibilite.numerique.gouv.fr#102]
Le nouveau site a supprimé beaucoup de contenus et a fait des choix pouvant avoir un impact sur l'interprétation de la loi qui peut avoir changé.

[EDIT] J'ai finalement retrouvé le contenu que je cherchais sur le nouveau site. Mis à part le suivi de version.

Pour une réelle transparence sur le suivi des évolutions, il est essentiel d'avoir accès aux archives des anciennes versions du RGAA (critères et tests mais aussi obligations d'accessibilité), et pas seulement sur GitHub, mais depuis un lien vers le site.

**Comment by design-gouv** [comment]
Bonjour @armonyaltinier 
Pouvez-vous nous préciser les nombreux contenus supprimés ainsi que les choix discutables évoqués ?

**Comment by armonyaltinier** [comment]
Bonjour @design-gouv 

Je vais corriger mon issue et vous prie de m'excuser pour la formulation accusatrice et injustifiée : j'ai finalement retrouvé les contenus que je pensais supprimés, mis à part la section sur les évolutions de version.

Je maintiens malgré tout l'importance d'avoir une traçabilité des évolutions du RGAA permettant d'avoir une vision claire des choix effectués.

**Comment by design-gouv** [comment]
Les notes de révision ont été ajoutées.
Une page _archives_ va également être ajoutée.
