### ISSUE TITLE
Critère 5.8 élements propres aux tableaux de données

### ISSUE THREAD

**Issue by cescarment** [DISIC/accessibilite.numerique.gouv.fr#113]
Bonjour,

J'avais proposé dans le précédent repo de supprimer l'élément `colgroup` du critère 5.8, voir les explications : https://github.com/DISIC/RGAA/issues/111

La proposition avait été acceptée dans le ticket. Pourtant, le critère 5.8 n'a pas été modifié sur le nouveau site RGAA.

**Comment by design-gouv** [comment]
Bonjour @cescarment 
Ce point a bien été pris en compte et est intégré à la prochaine mise à jour du référentiel.
