### ISSUE TITLE
Mettre les titres de critère sur le numéro du critère et le critère lui-même

### ISSUE THREAD

**Issue by alexarnaud** [DISIC/accessibilite.numerique.gouv.fr#118]
Bonjour,

Actuellement sur chaque critère les titres sont positionnés sur le numéro du critère. Pour moi, cela viole le critère RGAA "9.1" et le test 9.1.2, en effet, pour une personne mal-voyante ou aveugle, le numéro du critère n'est pas vraiment suffisant pour savoir de quel critère il s'agit.

Pourriez-vous s'il vous plait mettre le titre H3 sur à la fois le numéro du critère et la question associée/le critère ?

**Comment by design-gouv** [comment]
Bonjour,
Désolé pour le temps de réponse.
Ce point sera corrigé lors de la prochaine mise à jour prévue cette semaine.
