### ISSUE TITLE
Test 10.3.1 identique au 10.2.1 - Information présente vs compréhensible

### ISSUE THREAD

**Issue by PhilippeVay** [DISIC/accessibilite.numerique.gouv.fr#127]
Bonjour,

je suis à peu près sûr d'avoir déjà vu un retour à ce sujet (ancienne liste ou ancien dépôt ?) mais comme je ne vois pas de correction dans la mise à jour mineure qui s'annonce, le (re)voici : 

Le [test 10.3.1](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#10.3.1) est identique au test 10.2.1 (OK pour les critères), les deux parlent d'information devant rester présente alors que le critère 10.3 a pour sujet l'information compréhensible.
Le test 10.3.1 devrait être quasi-identique au critère 10.3.

C'était correct (différent) dans l'ancien dépôt : [ancien test 10.3.1](https://github.com/DISIC/RGAA/blob/master/v4.1/JSON/criteres.json#L2379)
[Test 10.3.1 actuel](https://github.com/DISIC/accessibilite.numerique.gouv.fr/blob/4.1.1/RGAA/4.1/criteres.json#L2394)

Actuellement on a : 

> 10.2 Dans chaque page web, le [contenu visible](https://accessibilite.numerique.gouv.fr/methode/glossaire/#contenu-visible) porteur d’information reste-t-il présent lorsque les [feuilles de styles](https://accessibilite.numerique.gouv.fr/methode/glossaire/#feuille-de-style) sont désactivées ?
> 10.2.1 Dans chaque page web, l’information reste-t-elle présente lorsque les [feuilles de styles](https://accessibilite.numerique.gouv.fr/methode/glossaire/#feuille-de-style) sont désactivées ?
>
> 10.3 Dans chaque page web, l’information **reste-t-elle [compréhensible](https://accessibilite.numerique.gouv.fr/methode/glossaire/#comprehensible-ordre-de-lecture)** lorsque les [feuilles de styles](https://accessibilite.numerique.gouv.fr/methode/glossaire/#feuille-de-style) sont désactivées ?
> 10.3.1 Dans chaque page web, l’information **reste-t-elle présente** lorsque les [feuilles de styles](https://accessibilite.numerique.gouv.fr/methode/glossaire/#feuille-de-style) sont désactivées ?

Bonne semaine !

**Comment by benoitdequick** [comment]
Merci @PhilippeVay pour le signalement.
