### ISSUE TITLE
Navigation au clavier dans les textarea

### ISSUE THREAD

**Issue by jchrabie** [DISIC/accessibilite.numerique.gouv.fr#131]
### Étapes pour reproduire
- Aller sur un textarea 
- Écrire du contenu
- Naviguer avec les flèches droite ou gauche

### Attendu
Pouvoir déplacer le curseur.

### Observé
Le curseur ne bouge pas.

**Comment by benoitdequick** [comment]
Bonjour @jchrabie 
Sur quelle page peut-on reproduire cette anomalie ?

**Comment by jchrabie** [comment]
Bonjour, 

Désolé de ne pas l'avoir indiqué : 

- Aller sur la réalisation d'un audit (ex : https://ara.numerique.gouv.fr/audits/[idAudit])
- Sur n'importe quel critère, cliquer sur "Conforme"
- Déplier "Commentaire (Optionnel)"
- Aller sur le textarea
- Écrire du contenu
- Naviguer avec les flèches droite ou gauche

Pour info, c'est la même chose lors du choix "Non conforme" sur "Description de l'erreur" ou sur "Recommendation de correction"

**Comment by benoitdequick** [comment]
Le mieux serait de faire l'iss
