### ISSUE TITLE
Prise en compte de la version la plus récente de l’article 47 de la loi n° 2005-102 du 11 février 2005

### ISSUE THREAD

**Issue by ChristianVOLLE** [DISIC/accessibilite.numerique.gouv.fr#146]
Bonjour,

[L’article 16 de la loi n° 2023-171 du 9 mars 2023](https://www.legifrance.gouv.fr/loda/id/LEGIARTI000047282795/2023-03-11/) a modifié l’article 47 de la loi n° 2005-102 du 11 février 2005.

Le lien fourni en réponse à la question « Quelle loi ? » est donc à mettre à jour.
Par ailleurs, [comme cela avait déjà été signalé en novembre 2022](https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/90), l’intitulé « quelle loi ? » doit être remplacé par « quels textes de référence ? ».

D’autre part, l[e paragraphe « contenus concernés » du RGAA](https://accessibilite.numerique.gouv.fr/obligations/champ-application/) doit être modifié puisqu’il indique, entre autres « Ne sont pas concernés les services de communication au public en ligne des fournisseurs de services de médias audiovisuels ».
Or la nouvelle version de l’article 47 ne comporte plus cette exception.

**Comment by design-gouv** [comment]
Bonjour,
l’article 16 de la loi n°2023-171 du 9 mars 2023 apporte une modification des dispositions dans l’article 47.
La référence à la loi ne change pas : c’est toujours l’article 47 de la Loi n° 2005-102 du 11 février 2005 qui s’applique pour les droits et l’égalité des chances des personnes handicapées.
La mise à jour du RGAA sera effectuée après adoption des décrets (et des arrêtés) d’application de la loi pour tenir compte de l’ensemble des modifications législatives et réglementaires.

Concernant l’intitulé de la question, le mot _loi_ a été utilisé car il est plus simple et plus clair.

**Comment by ChristianVOLLE** [comment]
Bonjour,

 

Je vous remercie pour la rapidité de votre réponse.

 


Prise en compte de la version la plus récente de l’article 47 de la loi n° 2005-102 du 11 février 2005


Il n’est pas contesté que l’article 47 de la loi de 2005 demeure le principal texte de référence, mais en réponse à la question « quelle loi ?», la réponse affichée sur le site ne se limite pas à la simple indication de cet article : elle fournit un lien et ce lien pointe vers une version caduque de l’article 47 alors que la nouvelle version date de plus de trois semaines.



 

Il apparaît étrange que le site public de référence relatif à l’accessibilité numérique fasse le choix de ne pas donner le lien vers la version à jour de cet article 47.

Une version 4.1.1 du RGAA a été mise en ligne le 4 avril, plus de trois semaines après l’entrée en vigueur de la nouvelle version de l’article 47.

Il était donc tout à fait possible de supprimer la mention désormais erronée « Ne sont pas concernés les services de communication au public en ligne des fournisseurs de services de médias audiovisuels » et de procéder aux autres éventuels ajustements nécessaires.

 

Si vous ne souhaitez pas mettre en ligne une nouvelle version du RGAA avant la parution de l'ensemble des modifications législatives et réglementaires, ce qui risque de prendre plusieurs semaines, voire plusieurs mois, il serait souhaitable, afin de ne pas les induire en erreur, que vous donniez, au minimum en page d’accueil, une information aux internautes pour les prévenir :

1.	Qu’une nouvelle version du RGAA est en cours de préparation ;
2.	Qu’en attendant cette publication, certaines mentions du RGAA se trouvent en contradiction avec la loi récemment modifiée.

 

S’agissant de la mention « quelle loi ? », je conçois le besoin de simplicité, mais la recherche de simplicité ne doit pas se faire au détriment de la précision. Pour refléter de manière simple et claire le contenu de la réponse le titre pourrait être « Quelle loi ? Quel décret ? »

Mais je conviens que c’est un domaine où entre une part de subjectivité et que ce type d’intitulé est beaucoup moins problématique qu’un lien vers une version caduque de la loi.

 


Autres signalements restés sans réponse


Pour mon signalement réf 146 <https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/146> , la réponse n’a pas correspondu à mes attentes, mais j’ai néanmoins apprécié d’avoir une réponse.

Tel n’a malheureusement pas été le cas de nombreux autres signalements que j’ai faits sur Github depuis novembre 2022.

Vous en trouverez le récapitulatif dans le tableau de suivi Excel ci-joint.

Sur 14 signalements effectués (réf 146 inclus) :

*	2 ont été totalement traités ;
*	2 ont été partiellement traités ;
*	10 n’ont pas été traités.

 

À part le cas du signalement 146, aucune réponse n’a été donnée pour les cas non traités ou traités de manière seulement partielle.

C’est là, de mon point de vue, une manière très cavalière de procéder de la part de la DINUM puisque c’est elle qui a invité à ce que soient faites des contributions sur Github.

Je trouve également très problématique qu’un site de référence tel que  accessibilite.numerique.gouv.fr <https://accessibilite.numerique.gouv.fr/>  ne respecte pas les obligations légales relatives à l’accessibilité :

*	présence de contenus non accessibles ;
*	taux de conformité surévalué et donc mention « Accessibilité : totalement conforme » injustifiée ;
*	absence de mention schéma pluriannuel de mise en accessibilité.

 

Je vous remercie donc par avance de bien vouloir fournir des réponses adaptées aux divers signalements mentionnés dans le tableau de suivi ci-joint.

 

Bien cordialement


 <http://www.avh.asso.fr/> 

Christian VOLLE

Chargé de mission accessibilité numérique


 

06 60 48 00 47  /   ***@***.***> ***@***.***

 <http://www.avh.asso.fr/> www.avh.asso.fr  <https://twitter.com/accnumVH> @accnumVH


 

 <https://www.facebook.com/AssociationValentinHauy/>  <https://twitter.com/ValentinHauy>  <https://www.youtube.com/user/AssoValentinHauy> 


 

Reconnue d’utilité publique depuis 1891 

Agréée par le Comité de la charte – Don en confiance

 

 


 <https://www.avh.asso.fr/fr/favoriser-laccessibilite/accessibilite-numerique/accessibilite-des-documents-et-des-courriels> Des documents et des courriels accessibles : pourquoi, comment ?

 <https://www.avh.asso.fr/fr/favoriser-laccessibilite/accessibilite-numerique/accessibilite-des-documents-et-des-courriels> ◄cliquez

 

 

 

De : Équipe design des services numériques ***@***.***> 
Envoyé : vendredi 7 avril 2023 08:18
À : DISIC/accessibilite.numerique.gouv.fr ***@***.***>
Cc : ChristianVOLLE ***@***.***>; Author ***@***.***>
Objet : Re: [DISIC/accessibilite.numerique.gouv.fr] Prise en compte de la version la plus récente de l’article 47 de la loi n° 2005-102 du 11 février 2005 (Issue #146)

 

Bonjour,
l’article 16 de la loi n°2023-171 du 9 mars 2023 apporte une modification des dispositions dans l’article 47.
La référence à la loi ne change pas : c’est toujours l’article 47 de la Loi n° 2005-102 du 11 février 2005 qui s’applique pour les droits et l’égalité des chances des personnes handicapées.
La mise à jour du RGAA sera effectuée après adoption des décrets (et des arrêtés) d’application de la loi pour tenir compte de l’ensemble des modifications législatives et réglementaires.

Concernant l’intitulé de la question, le mot loi a été utilisé car il est plus simple et plus clair.
