### ISSUE TITLE
Prise en compte de la version la plus récente de l’article 47 de la loi n° 2005-102 du 11 février 2005 et de l’article 47-1

### ISSUE THREAD

**Issue by ChristianVOLLE** [DISIC/accessibilite.numerique.gouv.fr#170]
Bonjour,

L’ordonnance n° 2023-859 du 6 septembre 2023 a :
•	**modifié l’article 47** de la loi n° 2005-102 du 11 février 2005 ; 
•	**ajouté un article 47-1** à cette même  loi

Le lien fourni en réponse à la question « Quelle loi ? », déjà obsolète depuis mats 2023 puisqu’il ne prenait pas en compte la version de l’article 47 issu de la loi n° 2023-171 du 9 mars 2023, est donc à modifier.
Il faut également ajouter le lien vers l’article 47-1.

D’autre part, bien qu’il y ait eu un signalement à ce sujet le 1er avril, le paragraphe « contenus concernés » du RGAA fournit toujours des informations erronées puisqu’il indique, entre autres « _Ne sont pas concernés les services de communication au public en ligne des fournisseurs de services de médias audiovisuels_ ».
Or, depuis le 9 mars 2023, l’article 47 ne comporte plus cette exception.
Ce passage du RGAA doit donc être corrigé.

Il est à espérer que ce signalement ne connaîtra pas le même classement vertical que [celui effectué le 1er avril sur un sujet similaire](https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/146).

**Comment by design-gouv** [comment]
Merci pour votre contribution.
Elle sera prise en compte ultérieurement.
