### ISSUE TITLE
Questions fréquentes – Qui est concerné ?

### ISSUE THREAD

**Issue by ChristianVOLLE** [DISIC/accessibilite.numerique.gouv.fr#171]
### Éléments de la rédaction actuelle :

- les organisations **légataires** d’une mission de service public ;
- les organisations d’intérêt général.

### Commentaires :
Malgré un [signalement effectué dès le 1er novembre 2022](https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/92), signalement classé verticalement sans aucune explication, la réponse fait toujours état des « organisations **légataires** d’une mission de service public ».
Il faudrait supprimer cette mention erronée et la remplacer par « organisations ### délégataires d’une mission de service public ».

Par ailleurs, la réponse n’apporte aucune information utile à propos de l’article 47 I-2°. 
Ce passage de l’article 47 est particulièrement complexe. 
Après maintes lectures, certains considèrent que ce passage assujettit à la loi **diverses associations œuvrant dans le domaine du handicap**, mais force est de constater que si plusieurs d’entre elles s’efforcent de rendre accessibles leurs services de communication au public en ligne, aucune, à notre connaissance, ne se sent concernée au point de respecter le triptyque des obligations déclaratives (schéma pluriannuel de mise en accessibilité, mention en page d’accueil, déclaration d’accessibilité).

Pour que la rubrique « questions fréquentes » présente un véritable intérêt, il serait souhaitable, que, sans viser l’exhaustivité, la réponse décrive précisément les catégories d’associations et de fondations relevant de l’obligation légale imposée par l’article 47.

Il est à noter que la rédaction actuelle « les organisations d’intérêt général » est erronée puisque son caractère général ne prend pas en compte le dernier alinéa de l’article 47 I « _Le présent article ne s'applique pas aux services de communication au public en ligne des organismes de droit privé à but non lucratif qui ne fournissent ni des services essentiels pour le public, ni des services répondant spécifiquement aux besoins des personnes handicapées ou destinés à celles-ci._ »

**Comment by design-gouv** [comment]
Merci pour votre contribution.
Elle sera prise en compte ultérieurement.
