### ISSUE TITLE
Questions fréquentes – Quels sites ? Contenu à modifier

### ISSUE THREAD

**Issue by ChristianVOLLE** [DISIC/accessibilite.numerique.gouv.fr#172]
Bonjour,

Ceci est la reprise d’un [signalement effectué le 2 novembre 2022](https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/94), signalement qualifié de « question » alors qu’il s’agissait du signalement d’une rédaction inadaptée, puis classé « terminé » le 10 février 2023, sans qu’aucun changement ait été apporté et sans explication. 

### Commentaires sur la rédaction actuelle
La rédaction n’est pas appropriée :

- l’intitulé « _quels sites ?_ » est restrictif par rapport à la loi qui parle de « _services de communication au public en ligne_ » ;
- dire que les applications mobiles ou le mobilier urbain numérique sont utilisés « _au travers d’un navigateur web_ » est déconnecté de la réalité technique ;
- le mobilier urbain numérique n’entre ni dans la catégorie des sites ni dans celle des applications ;
- il est fait l’impasse sur les publications sur les réseaux sociaux qui sont soumises à l’obligation d’accessibilité. L’observation des réseaux sociaux montre que cette obligation est très mal respectée. Ne pas évoquer le sujet ici est un obstacle à l’amélioration des pratiques. Il convient de souligner qu’il ne serait absolument pas pertinent de ne pas mentionner les publications sur les réseaux sociaux en alléguant qu’elles ne sont pas citées dans la directive 2016/2102. En effet, la directive 2016/2102 ne citait que les sites Internet et les applications mobiles du secteur public, pas les sites Internet de grandes entreprises, ni le mobilier urbain numérique. Comme elle en avait le droit, la France a choisi de faire une « surtransposition ». La loi ne se limite pas aux seuls sites Internet et applications mobiles. Elle parle de **services de communication au public en ligne** : « _L'accessibilité des services de communication au public en ligne concerne l'accès à tout type d'information sous forme numérique, quels que soient le moyen d'accès, les contenus et le mode de consultation, en particulier les sites internet, intranet, extranet, les applications mobiles, les progiciels et le mobilier urbain numérique pour sa partie applicative et interactive_ » **Compte tenu de de cette définition, il n’est pas contestable que les publications sur les réseaux sociaux faites par les organismes sont des « services de communication au public en ligne ».** Contrairement à ce que certains ont pu avancer à tort, l’obligation d’accessibilité ne pèse pas sur les plateformes, mais sur les organismes auteurs des publications. Dans le _Guide d’accompagnement du RGAA 3.0_, il était d’ailleurs indiqué « _Les contenus mis en ligne sur des sites externes sont le résultat d’une volonté du maître d’ouvrage d’atteindre le public via ces sites. Ils sont donc soumis à l’obligation d’accessibilité. Si la mise en ligne sur ces sites support a pour conséquence de rendre les contenus inaccessibles, c’est le producteur du contenu qui en sera responsable_ ».
- la formulation « _voir tous les contenus concernés_ » est trompeuse car elle laisse supposer que le lien pointe vers une liste exhaustive alors que ce n’est pas le cas.

### Modifications proposées :

**Intitulé de la question** : « Quels services de communication au public en ligne ? »

**Texte** :
« Sont notamment concernés :

- les sites internet, intranet, extranet ;
- les progiciels utilisés au travers d’un navigateur web ou d’une application mobile ;
- le mobilier urbain numérique ;
- les publications faites sur les réseaux sociaux. »

**Comment by design-gouv** [comment]
Merci pour votre contribution.
Elle sera prise en compte ultérieurement.
