### ISSUE TITLE
Questions fréquentes – Quelles sanctions ? Contenu à revoir complètement

### ISSUE THREAD

**Issue by ChristianVOLLE** [DISIC/accessibilite.numerique.gouv.fr#173]
Bonjour,

Le contenu de la réponse à la question « _Quelles sanctions ?_ » est à revoir complètement afin de prendre en compte les nouvelles dispositions introduites par l’article 47-1 de la loi n° 2005-102 du 11 février 2005 :

- rôle d’autorité de contrôle et de sanction confié à **l’ARCOM**
- **sanction pécuniaire des défauts d’accessibilité** pouvant atteindre 50 000 €

**Comment by design-gouv** [comment]
Merci pour votre contribution.
Elle sera prise en compte ultérieurement.
