### ISSUE TITLE
Le site accessibilite.numerique.gouv.fr n’est pas totalement conforme au RGAA

### ISSUE THREAD

**Issue by ChristianVOLLE** [DISIC/accessibilite.numerique.gouv.fr#174]
Bonjour,

Ceci est la reprise d’un [signalement effectué le 2 novembre 2022](https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/98), signalement qualifié de « question » alors qu’il s’agissait du signalement d’une non conformité au RGAA, puis classé « terminé » le 10 février 2023, sans qu’aucun changement ait été apporté et sans explication.

### Constats et commentaires
La déclaration d’accessibilité fait état d’une totale conformité au RGAA 4.
Dans le document [Observations relatives à l’audit de conformité de accessibilite.numerique.gouv.fr](https://www.dropbox.com/s/uxcugbsw0dfz5jw/Observations%20relatives%20%C3%A0%20l%E2%80%99audit%20de%20conformit%C3%A9%20de%20accessibilite.numerique.gouv.fr.docx?dl=0) envoyé le 7 décembre 2022 à la DINUM, il était indiqué que cette allégation d’une conformité à 100 % était abusive. D’une part, l’échantillon n’avait pas été constitué correctement puisqu’il ne comportait pas « au moins un document téléchargeable pertinent, le cas échéant, pour chaque type de service fourni et pour toute autre utilisation principalement prévue ».
D'autre part, l’échantillon comportait cependant la page [Kits d’audits](https://accessibilite.numerique.gouv.fr/ressources/kit-audit/). Or l’audit n’a pas relevé les défauts d’accessibilité présents dans trois documents :

- [Modèle de rapport d’audit](https://accessibilite.numerique.gouv.fr/doc/rgaa4-2019-modele-rapport-audit.odt)
- [Exemple de déclaration d’accessibilité RGAA](https://accessibilite.numerique.gouv.fr/doc/rgaa4-2019-exemple-declaration.odt)
- [Modèle de grille d’audit RGAA version 4.1](https://accessibilite.numerique.gouv.fr/doc/rgaa4.1.modele-de-grille-d-audit.ods)

Tous les défauts signalés en décembre 2022 sont encore présents à l’exception d’un seul : dans le modèle de rapport d’audit, il y avait une image non décrite (et faisant curieusement référence non à la DINUM, mais au secrétariat général pour la modernisation de l'action publique). Cette image a été supprimée dans la version de mars 2023.
En revanche, les autres défauts des documents du kit d’audit subsistent :
grille d’audit non lisible sur tablette et smartphone
cellules fusionnées ;
utilisation inappropriée des titres dans les documents texte.

### Mesures correctives souhaitées
De notre point de vue, il faut

1. Soit réaliser un nouvel audit identifiant bien tous les défauts d’accessibilité et publier une nouvelle déclaration d’accessibilité avec un taux de conformité revu à la baisse ;
2. Soit corriger les défauts d’accessibilité signalés.

Compte tenu de la très faible charge représentée par la solution 2, c’est évidemment celle-ci qui nous apparaît préférable. **Les documents relatifs à l’accessibilité doivent en effet être eux-mêmes accessibles.**

**Comment by design-gouv** [comment]
Merci pour votre contribution.
Elle sera prise en compte ultérieurement.
