### ISSUE TITLE
Lien de téléchargement incorrect

### ISSUE THREAD

**Issue by astranchet** [DISIC/accessibilite.numerique.gouv.fr#43]
Sur la page Ressources > [Kit d'audit](https://accessibilite.numerique.gouv.fr/ressources/kit-audit/), quand je clique sur le lien [Modèle de grille d’audit RGAA version 4.1, format ODS (233 Ko)](https://accessibilite.numerique.gouv.fr/doc/rgaa4.1.modele-de-grille-d-audit.ods), je tombe sur une erreur 404 
![Page Not Found](https://user-images.githubusercontent.com/1374389/169039269-30754e70-8121-478b-b483-ddaee6fda2a9.png)

**Comment by benoitdequick** [comment]
Tout à fait.
Le correctif sera dans la prochaine livraison ;)

**Comment by benoitdequick** [comment]
Livraison imminente
