### ISSUE TITLE
Version du référentiel utilisée...

### ISSUE THREAD

**Issue by sbonaventure** [DISIC/accessibilite.numerique.gouv.fr#57]
Bonjour,

Je m'interroge quand à la version du référentiel utilisée pour ce site, qui ne semble pas être celle du RGAA 4.1

En effet, je constate par exemple que pour le test 1.3.6, la première condition du test est la suivante : 
>S’il est présent, le contenu de l’**attribut** title est pertinent ;

Alors que sur le site actuel (https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#test-1-3-6), il est indiqué : 
> S’il est présent, le contenu de l’**élément** ``<title>`` est pertinent ;

Par ailleurs, la note de révision du RGAA 4.0 vers RGAA 4.1(https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/notes-revision-rgaa4.0-rgaa4.1/#contenu) indique bien
> Modification de la première condition du test 1.3.6 (issue #39) :
“S’il est présent, le contenu de l’attribut title est pertinent.”
est remplacée par :
“S’il est présent, le contenu de l’élément ``<title>`` est pertinent.”

Pour autant, ce n'est pas non plus le RGAA 4.0 qui est utilisé, car certaines des modifications indiquée par la note de révision, comme par exemple sur le test 1.1.6 sont bien présentes.

**Comment by juliemoynatPro** [comment]
Il n'y a pas que ça qui a changé. À certains endroits (pas tous), le mot "balise" a été changé en "élément". C'est le cas pour les critères 1.1 et 1.2 par exemple. Pour le 1.3, en revanche, il n'y a que pour `<img>` qu'il est question d'élément mais pas pour area, embed, canvas, etc. Puis pour les autres critères, c'est "balise" comme dans le référentiel officiel.

Vraiment curieux car le référentiel n'est pas censé avoir été modifié si j'en crois ce tweet : https://twitter.com/design_gouv/status/1549405164263686147

**Comment by benoitdequick** [comment]
Bonjour à tous les deux,
Merci @sbonaventure, la résolution de ce sujet est actuellement en cours.
Merci @juliemoynatPro, ce point est bien pris en compte : https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/69#issuecomment-1209116538
