### ISSUE TITLE
Absence des notes de révision

### ISSUE THREAD

**Issue by sbonaventure** [DISIC/accessibilite.numerique.gouv.fr#58]
Les notes de révision ne sont plus disponible alors que ces pages existent sur le site actuel :
* https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/notes-revision-rgaa3-rgaa4.0/
* https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/notes-revision-rgaa4.0-rgaa4.1/

Il serait indispensable à mon sens de les remettre à disposition.

**Comment by benoitdequick** [comment]
Bonjour @sbonaventure,
Pouvez-vous nous expliciter en quoi ces notes de révisions vous seraient indispensables ?

Je vous remercie

**Comment by sbonaventure** [comment]
Alors sur les anciennes notes de révision, cela m'a permis notamment de pouvoir mettre a jour des outils tel que l'assistant RGAA que nous maintenons à Empreinte Digitale.

A la vue des commentaires ou échanges sur les issues, je pense qu'il est indispensable de produire une nouvelle note de révision lorsque ce nouveau site sortira afin que les différents éditeurs d'outils qui se basent sur le RGAA puissent se mettre à jour

**Comment by benoitdequick** [comment]
Bonjour @sbonaventure 
Il va de soi que les versions futures du RGAA seront accompagnées de notes de révision.

La note de révision du RGAA4.0 vers 4.1 va bien être reprise. Mais pas celle du RGAA 3 vers 4.
