### ISSUE TITLE
Section "obligations" sur la page d'accueil

### ISSUE THREAD

**Issue by jpv66** [DISIC/accessibilite.numerique.gouv.fr#62]
Bonjour,

Sur la page d'accueil dans les questions fréquentes, la section "obligations" comporte les obligations suivantes :

> **Pour chaque service en ligne doivent figurer :**
> 
> -     une [déclaration d’accessibilité](https://accessibilite.numerique.gouv.fr/obligations/declaration-accessibilite) ;
> -     un [schéma d’accessibilité numérique](https://accessibilite.numerique.gouv.fr/obligations/schema-pluriannuel) ;
> -     la [mention de la conformité en page d’accueil](https://accessibilite.numerique.gouv.fr/obligations/mentions-et-pages-obligatoires).

Je suis très surpris de ne pas voir y figurer l'obligation pour les sites et applications concernées d'être conforme au RGAA ce qu me semble être au coeur de la loi.

**Comment by benoitdequick** [comment]
Bonjour @jpv66,

Merci pour cette remarque.
En effet, ça sera corrigé très vite.
