### ISSUE TITLE
Menu des thématiques de critères non "sticky"

### ISSUE THREAD

**Issue by yaaax** [DISIC/accessibilite.numerique.gouv.fr#64]
Vu sur la page : https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/

Le menu de gauche "Thématiques" devrait être _sticky_, or il ne l'est plus.
Le problème semble venir du code CSS suivant :
```
main {
    overflow: hidden
}
```
En supprimant `overflow: hidden`, le menu redevient _sticky_.

**Notes :**
- ce code n'est plus sur la branche _dev_
- vérifier à quoi servait le code `main { overflow: hidden }`

**Comment by benoitdequick** [comment]
Merci @yaaax pour cette alerte.
Le fix va passer dans la prochaine livraison ;)
