### ISSUE TITLE
Les obligations légales organisées par type d'acteurs ?

### ISSUE THREAD

**Issue by maiwann** [DISIC/accessibilite.numerique.gouv.fr#65]
Bonjour,

Le bloc menant à la page "Obligations légales" est sous-titré "Qui est concerné par le RGAA ? Quelles sont les obligations légales à respecter ?"

Aussi, en cliquant sur la page, je m'attendais à une organisation selon les "types d'acteurs" (Acteur public, acteur privé de plus de xxx, etc…) qui donneraient les différentes obligations légales selon le profil des acteurs.

En découvrant la page, je me suis sentie perdue face à des termes que je ne comprenais pas (Notion d’accessibilité numérique, Rappel du champ d’application, Évaluation de la conformité à la norme de référence…) et ai eu l'impression qu'il s'agissait de 6 types d'obligations légales différentes, et que je devais lire chaque page pour savoir si j'étais concernée ou non par leur mise en application, ce qui m'a semblé fastidieux d'un prime abord (et j'en suis restée là).

Après relecture, je réalise que sur ces 6 blocs, il y a 3 éléments de "définition" et 3 autres qui parlent précisément de ce qui est attendu. J'ai mis du temps et la lecture de plusieurs pages pour réaliser cette confusion :)

En espérant que ce retour vous permettra d'améliorer cette page, bon courage pour la suite !

**Comment by benoitdequick** [comment]
Bonjour @maiwann,
Merci pour votre retour.
Le RGAA n‘est effectivement pas facile d’accès. Il est toutefois compliqué d’apporter des modifications structurantes à des textes légaux ; cependant nous essayons d’accompagner sa prise en main sur notre site [design.numerique.gouv.fr/accessibilite-numerique](https://design.numerique.gouv.fr/accessibilite-numerique/). 
Nous étudions comment mieux lier les deux.
