### ISSUE TITLE
Changelog sur les opérations de modifications des critères et des tests

### ISSUE THREAD

**Issue by jpv66** [DISIC/accessibilite.numerique.gouv.fr#67]
Bonjour,

A la lecture des critères et des test on s'aperçoit que des modification ont été effectuées dans leurs rédactions.
La nouvelle version disposera-t-elle d'un changelog permettant d'identifier les modifications effectuées sur les critères et les tests et les raisons de celles-ci.
Certaines d'entre-elles sont susceptible de modifier le périmètre ou la portée d'un critère, la publication d'un changelog est indispensable pour suivre ce type de modification.

**Comment by benoitdequick** [comment]
Bonjour @jpv66,
Aucune modification autre que d'ordre orthotypographique n'a été effectuée. Ces correctifs n'ont pas vocation à alimenter un changeLog.
Bonne journée et à bientôt :)
