### ISSUE TITLE
Modification test 1.1.8 condition 3

### ISSUE THREAD

**Issue by jpv66** [DISIC/accessibilite.numerique.gouv.fr#68]
Bonjour,

Le test 1.1.8 à été modifié sur le nouvelle version du RGAA :

### RGAA 4.1 test 1.1.8 - condition 3 :

"L’élément `<canvas>` est immédiatement suivi d’un lien ou bouton adjacent permettant d’accéder à un contenu alternatif"

Ce qui correspond à ce modèle de code : 
`<canvas>[...]</canvas><a href="">[...]</a>`

### RGAA 4.1 [béta] test 1.1.8 - condition 3 :
La balise ouvrante `<canvas>` est immédiatement suivie d’un lien ou bouton adjacent permettant d’accéder à un contenu alternatif ;

Ce qui correspond à ce modèle de code :
`<canvas><a href="">[...]</a>[...]</canvas>`

Pourriez-vous expliquer les raisons de cette modification ?

**Comment by benoitdequick** [comment]
re-bonjour @jpv66 
Même remarque https://github.com/DISIC/accessibilite.numerique.gouv.fr/issues/69
