### ISSUE TITLE
Logique d'utilisation entre "élément" et "balise"

### ISSUE THREAD

**Issue by jpv66** [DISIC/accessibilite.numerique.gouv.fr#69]
Quelle logique a été utilisée pour déterminer l'utilisation du terme "élément" ou "balise".

Par exemple :

### Critère 1.2.4 condition 1 :
L’élément `<svg>` possède un attribut WAI-ARIA `aria-hidden="true"` ;

### Critère 1.2.5 condition 2 :
La balise ouvrante `<canvas>` possède un attribut WAI-ARIA `aria-hidden="true" ;`

Qu'elle est la différence entre ces deux conditions de tests qui conduit à les écrire de manière différente ?

A noter que dans la version actuelle les deux tests sont écrits de la  même manière :

La balise `<svg>` possède un attribut WAI-ARIA `aria-hidden="true"` ;
La balise `<canvas>` possède un attribut WAI-ARIA `aria-hidden="true"` ;

Il y a plein d'autres exemples :

### Critère 1.1.6 condition 1
La balise ouvrante `<object>` possède une alternative textuelle et un attribut role="img" ;

### Critère 1.1.7 condition 1
L’élément `<embed>` possède une alternative textuelle et un attribut role="img" ;

**Comment by benoitdequick** [comment]
Bonjour @jpv66,

Merci pour ce retour. Effectivement, dans la version initiale, nous avons utilisé le terme d’élément alors que balise aurait été dans certains cas plus pertinent.
Nous avons commencé à revoir cet aspect mais nous allons revenir à la version initiale car il n'est pas possible de modifier un texte légal de cette manière. 
Nous avons bien noté ce point pour la prochaine version du référentiel.
