### ISSUE TITLE
Contenu de la section ressources 

### ISSUE THREAD

**Issue by sbonaventure** [DISIC/accessibilite.numerique.gouv.fr#70]
Le contenu de la section "ressources" : https://accessibilite.numerique.gouv.fr/ressources/ ne cite comme ressources que les contenus suivants : 

- [Documents de référence](https://accessibilite.numerique.gouv.fr/ressources/references)
- [Kit d’audit](https://accessibilite.numerique.gouv.fr/ressources/kit-audit)
- [Méthodologie de test](https://accessibilite.numerique.gouv.fr/ressources/methodologie-de-test)
- [Exemple de déclaration d’accessibilité](https://accessibilite.numerique.gouv.fr/ressources/modele-de-declaration)
- [Questions](https://accessibilite.numerique.gouv.fr/ressources/questions) qui en réalité renvoi vers la liste de diffusion sur RENATER

Cependant, je me dis qu'une partie des liens de la page outils du site https://design.numerique.gouv.fr/outils/ pourrait être mentionné dans cette section ressources, non ?

**Comment by sbonaventure** [comment]
Par ailleurs en ce qui concerne les ressources, je regrette toujours que les ressources produites autour du RGAA 3 n'aient pas été mises à jour. Même si elles n'ont pas de MAJ de prévu, il me semble important d'indiquer qu'elles existent toujours !! Access42 avait publié un tableau récapitulatif des ressources produites lors de la publication du RGAA3  : https://fr.slides.access42.net/gta2017/2/ressources/

Sans évoquer la mise à jour de ces ressources (bien que je soit enchanté si certaines d'entre elles soit MAJ), mais il serait pertinent à mon sens de les mentionner comme étant des ressources disponibles (avec toutes les précautions nécessaire quand à la version du RGAA auxquelles elles font référence).

**Comment by benoitdequick** [comment]
Bonjour @sbonaventure,
À ce stade, seuls les contenus existants ont été repris. 
Nous allons voir comment lier les deux sites.

Concernant les guides RGAA3, ils sont mentionnés sur https://design.numerique.gouv.fr/outils/. Leurs mises à jour sont à l'étude. 

À suivre.

**Comment by anais0210** [comment]
Bonjour, 

pour rebondir sur les ressources. 
Est ce que ce ne serait pas pertinent de proposer le [WCAG](https://www.w3.org/Translations/WCAG21-fr/) traduit par access42 ?

**Comment by benoitdequick** [comment]
Bonjour @anais0210,
C'est une excellente idée !
Et même déjà le cas dans la page documents de références et au niveau de chaque critère ;)
