### ISSUE TITLE
Absence des liaisons à la norme de référence.

### ISSUE THREAD

**Issue by jpv66** [DISIC/accessibilite.numerique.gouv.fr#71]
Bonjour,

Dans la version proposée je remarque que les correspondances avec la norme EN 301 549 V2.1.2 (2018-08) sont absentes.

Est-ce fait exprès et, le cas échéant, qu'elle en est la justification, la norme européenne étant la référence règlementaire.

**Comment by benoitdequick** [comment]
Bonjour @jpv66,
Ce point est bien noté et sera corrigé à la prochaine livraison.
