### ISSUE TITLE
Modifier les correspondance WCAG avec la traduction française ?

### ISSUE THREAD

**Issue by luce-carevic** [DISIC/accessibilite.numerique.gouv.fr#77]
Bonsoir,

Maintenant que la traduction française agréée des WCAG (https://www.w3.org/Translations/WCAG21-fr/#abstract) a été publiée, est-ce qu'il ne serait pas pertinent de modifier les correspondances et de relier sur la version française pour les personnes qui utilisent le RGAA ?

**Comment by benoitdequick** [comment]
Bonjour @luce-carevic 
Tout à fait.
C‘est bien prévu :)

**Comment by luce-carevic** [comment]
Super ! Merci pour le retour :)
